spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: file:///tmp/config
server:
    port: 8888
management:
    security:
        enabled: false